//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTRABZONEntities4 : DbContext
    {
        public DBTRABZONEntities4()
            : base("name=DBTRABZONEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLADMİN> TBLADMİN { get; set; }
        public virtual DbSet<TBLDOGA> TBLDOGA { get; set; }
        public virtual DbSet<TBLGİRİS> TBLGİRİS { get; set; }
        public virtual DbSet<TBLILETİSİM> TBLILETİSİM { get; set; }
        public virtual DbSet<TBLKULTUR> TBLKULTUR { get; set; }
        public virtual DbSet<TBLTARİH> TBLTARİH { get; set; }
    }
}
