//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDOGA
    {
        public int DogaID { get; set; }
        public string DogaBaslik1 { get; set; }
        public string DogaBaslik2 { get; set; }
        public string DogaText { get; set; }
        public string DogaImageURL { get; set; }
    }
}
