//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTARİH
    {
        public int TarihID { get; set; }
        public string TarihBaslık { get; set; }
        public string TarihImageURL { get; set; }
        public string TarihText { get; set; }
    }
}
